[workspace]
members = [
    "async-coap",
    "async-coap-uri",
	"async-coap-uri/proc-macros",
    "async-coap-tokio",
]
default-members = [
    "async-coap",
    "async-coap-uri",
    "async-coap-tokio",
]
